### ISSUE TITLE
Neispravna poveznica na sliku u README.md ?

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Voltage---current-sensor-INA219-breakout-hardware-design#1]
https://github.com/SolderedElectronics/Voltage---current-sensor-INA219-breakout-hardware-design/blob/ec33d60d32f21b6328748ade8ca24d4f7acbeeaa/README.md?plain=1#L5

umjesto:

https://github.com/SolderedElectronics/Voltage-&-current-sensor-INA219-breakout-hardware-design/blob/main/OUTPUTS/V1.1.1/333066.jpg?raw=true

čini mi se da bi trebalo biti:

https://github.com/SolderedElectronics/Voltage---current-sensor-INA219-breakout-hardware-design/blob/main/OUTPUTS/V1.0.0/333066.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
